#!/usr/bin/env bash
# Displaying numbers from 1 to 100 in list format.
#  "FizzBuzz" when the number is a multiple of 3 and 5.
#  "Fizz" when the number is a multiple of 3.
#  "Buzz" when the number is a multiple of 5.
#  Otherwise, displaying the number.
counter=0
while ((counter++<100)); do
    if (( counter % 3 == 0 && counter % 5 == 0 )); then
        echo "FizzBuzz"
    elif (( counter % 3 == 0 )); then
        echo "Fizz"
    elif (( counter % 5 == 0 )); then
        echo "Buzz"
    else
        echo $counter
    fi
done
