#!/usr/bin/env bash
# This script displaying "Best School" 10 times then hi in 9th.
counter=0
while ((counter++<10)); do
    echo "Best School"
    if [[ $counter -eq 9 ]]; then
        echo "Hi";
    fi
done
